env:
  browser: true
  es6: true
settings:
  react:
    version: detect
extends:
  - 'plugin:react/recommended'
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
parser: babel-eslint
plugins:
  - react
  -  prettier
rules:
  indent:
    - 'error'
    - 4
    - SwitchCase: 1
  no-underscore-dangle: 'off'
  object-curly-newline: 'off'
  implicit-arrow-linebreak: 'off'
overrides:
  - files:
      - "**/*.test.js"
      - "**/*.test.jsx"
    env:
      jest: true

